### ISSUE TITLE
Skip small files: But how small?!?

### ISSUE THREAD

**Issue by jedie** [jedie/PyHardLinkBackup#15]
e.g.: NTFS stores files smaller than 1KB directly into MFT, see: http://blogs.technet.com/b/askcore/archive/2009/10/16/the-four-stages-of-ntfs-file-growth.aspx

ext4 has the "inline data", too: https://ext4.wiki.kernel.org/index.php/Ext4_Disk_Layout#Inline_Data

Every file will also make the SQLite DB around ~300Bytes bigger.

So how small must be a file, that a hardlink will consume more/equal space?!?

**Comment by jerch** [comment]
If you really can save any space by treating those small files differently is IMHO a matter of how many linked backups you want to keep - If I understand the ext4 inline data description correctly, with some assumptions like inode size of 256 bytes and a typical block size of 4096 bytes your break even would be at x saves of a file fitting into the inline record:
x * 256 + 300 + 4096 = x * (256 + 300)
256 + 4396 / x = 556
4396 = 300 * x
x = 14.6

This means any file fitting into the inline data will take less space with real hardlinks (inode + block data) if it got saved more than 14 times. This will change with a different block size (just replace the 4096 with the real block size). Not sure if the inode size can change at all.

**Comment by jedie** [comment]
Maybe... But what's the consequence?

Think a rule like: `if hadlink.count()>14: no more hardlinks` is absurd, isn't it?

One missing aspect is: How much space consume a hardlink on NTFS, ext4 etc.
Will a hardlink consume on NTFS 1KB (One MFT entry) and on ext4 256Bytes (One file inote size?)


And interesting question is: How much faster is `if file.size<X: Don't hit database, just use filecopy()`
This is also a question of: How many small files are there...

**Comment by jerch** [comment]
Ok I was wrong about how hardlinks are saved in ext4 - they wont take an inode but a so called directory entry. The size of those is really small, I couldnt find any further data about the exact size. Ppl keep telling that hardlinks are much more efficient spacewise than symlinks which indicates that the space taken is less than one file in the inline data (a symlink will mostly likely fit into it since it is just another inode with the path string).
The speed question is kinda orthogonal to the space thing, accessing the database will always lead to some overhead.

**Comment by jedie** [comment]
In the other side: if we exclude files from the database: we can't find them via the database...

And something like: make a list of all changed files must handle the excluded files also in a different way...

And non developer will maybe not so much small files...

**Comment by jerch** [comment]
IMHO you wont save much to no space by avoiding hardlinks for tiny files and you would have to respect the FS circumstances which will bloat your code. Sounds to me like a path not worth taking.

About the database - this depends on how much your backups rely on the data in the database. If you can avoid the database, perfect, it will save you space and time. But then you will have to make sure that you can restore all needed information from elsewhere. This should be always the case for backups onto the same FS type and carefully moving all attributes but gets tricky if you try to backup some FS to another FS - it is likely that some attributes cant be stored along with the files and would need an additional data storage.

About saving process time - since a backup process relies heavily on IO you cant save much time for new files. For old unchanged files you probably can gain some speed by using a non cryptographic hash algorithm for the comparison. This is still IO heavy since it needs to load both files and rehash them. rsync uses mtime as default to avoid rehashing at all.

**Comment by jedie** [comment]
I come to the conclusion: to do nothing special for small files...

btw. rebuilding the database is possible with "phlb add", see: https://github.com/jedie/PyHardLinkBackup#add-missing-backups-to-database
